### ISSUE TITLE
explicit permissions import from Products.CMFCore is needed

### ISSUE THREAD

**Issue by 1letter** [webcloud7/wcs.samlauth#6]
in Plone 6.1. the permission import in configure.zcml is needed:

```
<include package="Products.CMFCore" file="permissions.zcml" />
```

**Comment by maethu** [comment]
Hey @1letter 

Thanks for reporting. 
I just released version 1.0.0b1 https://pypi.org/project/wcs.samlauth/1.0.0b1/  and add automated tests for plone 6.1.0a5. 

Cheers, 
Mathias
